

import org.eclipse.rdf4j.repository.sail.SailRepository;

public enum REPO_TYPES {
	MEMORY_SIMPLE,
	MEMORY_WITH_LUCENE_INDEX_IN_RAM,
	MEMORY_WITH_LUCENE_INDEX_IN_FILE,
	NATIVE_SIMPLE,
	NATIVE_WITH_LUCENE_INDEX_IN_RAM,
	NATIVE_WITH_LUCENE_INDEX_IN_FILE

}
